Draft: Add tests and docs for environment variable resolution.
meltano/meltano pull request #5938
Opened 2022-05-30 17:58 UTC by MeltyBot

Migrated from GitLab: https://gitlab.com/meltano/meltano/-/merge_requests/2667

Originally created by @cjohnhanson on 2022-05-26 21:59:55

---

## Merge Request Checklist

- [X] Link to an issue
- [X] Include the proposed fix or feature
- [X] Include and update tests for the modified code
- [X] Include a documentation change
- [X] Add a [CHANGELOG.md](https://gitlab.com/meltano/meltano/blob/master/README.md#Changelog) entry in the Unreleased section for any user-facing changes
- [X] Mention or assign a maintainer

Closes #3173

2022-06-01 15:01 UTC, tayloramurphy requested changes
@aaronsteers @cjohnhanson I'm realizing that the configuration page https://docs.meltano.com/guide/configuration doesn't mention the `env:` key _at all_... 

@cjohnhanson I think for this PR we need something in the `Environment variables` section  that mentions that key. 

@aaronsteers so as not to completely blow up scope on the PR, I can open an additional issue around the env key since we currently have that info scattered all around.

2022-06-01 15:03 UTC, tayloramurphy commented
@aaronsteers I opened https://github.com/meltano/meltano/issues/5969

2022-06-02 00:12 UTC, cjohnhanson commented on docs/src/_reference/command-line-interface.md
> +meltano invoke --print-environment-variable PLUGIN_ENVIRONMENT_VARIABLE_1 --print-environment-variable PLUGIN_ENVIRONMENT_VARIABLE_2
Yep they definitely are, I added a placeholder plugin for these examples.

2022-06-02 00:38 UTC, cjohnhanson commented
@aaronsteers - 
> Do you mind adding summary of tests/changes here, and especially if there are any additional tasks or issues to resolve?

Sure thing, the high-level takeaway is that there are 7 tests which currently `xfail` (rather than hard fail, which is why you won't see these failures in the pipeline, they'll show as `XFAIL`s in pytest output). These 7 tests can be resolved by addressing two underlying causes.

Shell environment variables take too high of precedence compared to what is described in the miro board, I'll create a follow-up issue for that which will resolve 6 of the currently `xfail'-ing tests. 

Inheritance (e.g., setting a `STACKED` env var to `1` and then `{STACKED}2`, etc.)  also basically doesn't work at all as expected. I'll create another follow-up issue to address that which will resolve the one remaining failing test case. 

To be clear though, the behavior _is_ in line with what our docs _currently_ say, but not with the new model as described in the miro board.

> and/or are there any other caveats that should be called out before merging this PR and closing the related issue?
I still need to address this feedback from @tayloramurphy :
> @cjohnhanson I think for this PR we need something in the Environment variables section that mentions that key.

See also this comment in the gitlab MR for some more details:
> The tests I've written are in line with my reading of the "New: Simplified Model" for precedence in [the miro board](https://miro.com/app/board/uXjVO3j_ADw=/), but differ significantly from current behavior. The tests corresponding to the scenarios in which current behavior is out of line with desired behavior are currently set to `xfail` and are parametrized with human-readable scenario descriptions to facilitate this follow-up work. The current behavior for precedence matches what's currently in [the docs](https://docs.meltano.com/guide/configuration#configuration-layers), though I added a short clarification on environment-level precedence for plugin settings.The tests I've written are in line with my reading of the "New: Simplified Model" for precedence in [the miro board](https://miro.com/app/board/uXjVO3j_ADw=/), but differ significantly from current behavior. The tests corresponding to the scenarios in which current behavior is out of line with desired behavior are currently set to xfail and are parametrized with human-readable scenario descriptions to facilitate this follow-up work. The current behavior for precedence matches what's currently in [the docs](https://docs.meltano.com/guide/configuration#configuration-layers), though I added a short clarification on environment-level precedence for plugin settings.

2022-06-02 00:54 UTC, cjohnhanson commented
@aaronsteers @tayloramurphy I'm hoping to get to a PR tonight for my one other remaining 2.0 issue. So if I misunderstood scope here and we need to try to address one or both of the resolution/inheritance issues I outlined in my above comment, I can push to get that taken care of in the next couple days, or potentially stretching into Monday of next week.

2022-06-02 02:10 UTC, aaronsteers commented
@cjohnhanson - Re: 

> These 7 tests can be resolved by addressing two underlying causes.
> 
> Shell environment variables take too high of precedence compared to what is described in the miro board, I'll create a follow-up issue for that which will resolve 6 of the currently `xfail'-ing tests.
> 
> Inheritance (e.g., setting a STACKED env var to 1 and then {STACKED}2, etc.) also basically doesn't work at all as expected. I'll create another follow-up issue to address that which will resolve the one remaining failing test case.

Thanks very much for this additional detail. I really like the approach of using xfail tests so we can keep those in the codebase and work those towards resolution.

> So if I misunderstood scope here and we need to try to address one or both...

Actually, I think you've got the scope perfectly. If I understand correctly, there are basically three todos I'd ask before closing:

1. [ ] Create new issues for those 2 follow-on fixes as described above (and link them in a comment here for ref).
2. [ ] Can we add inline refs for each respective xfail tests, linking in a code comment to the logged issue that is expected to fix the failing test.
3. [ ] Not covered above, but I see failing tests still in pytest suite on GitLab. Is there additional work needed to get these to pass? https://gitlab.com/meltano/legacy-ci/meltano/-/jobs/2536112067

I think with these three items resolved, we can close. What I can't speak to yet is whether we'll move to prioritize either of the two new issues. I'll wait to review those more closely before I and @tayloramurphy try to make a call on relative priority. (If you feel like you can add a `weight` estimate on each, that could be very helpful.)

2022-06-02 02:11 UTC, aaronsteers commented
```
>       assert len(result_no_ff.settings) == 11  # noqa: WPS432
E       assert 12 == 11
```

2022-06-02 12:09 UTC, cjohnhanson commented
@aaronsteers there was some additional work needed to get these to pass -- I had introduced a regression in a recent commit.

Those specific failing tests are passing locally now. I'll check in on the pipeline later today and get those issues created and then add the inline refs next to the xfails, and then this should be good to merge+close today.

2022-06-02 17:23 UTC, edgarrmondragon approved these changes

2022-06-02 18:01 UTC, cjohnhanson commented
@tayloramurphy is this what you had in mind for a quick blurb about `env:` key?
https://github.com/meltano/meltano/pull/5938/files#diff-627749b70e154d1698d041017804e255927fac4cac7383dd6ee3fd6fd05a3b70L128

2022-06-02 18:03 UTC, tayloramurphy commented
> @tayloramurphy is this what you had in mind for a quick blurb about `env:` key? https://github.com/meltano/meltano/pull/5938/files#diff-627749b70e154d1698d041017804e255927fac4cac7383dd6ee3fd6fd05a3b70L128

@cjohnhanson yep! That looks great - I have #5969 to track adding more 👍

2022-06-02 18:03 UTC, tayloramurphy approved these changes

2022-06-02 19:17 UTC, merged

2022-06-02 19:40 UTC, aaronsteers commented
@cjohnhanson - re:

> is this what you had in mind for a quick blurb about env: key?
> https://github.com/meltano/meltano/pull/5938/files#diff-627749b70e154d1698d041017804e255927fac4cac7383dd6ee3fd6fd05a3b70L128


Love this! Thanks!