Add telemetry for `meltano config`
meltano/meltano pull request #6137
Opened 2022-06-09 20:31 UTC by pandemicsyn

2022-06-09 20:59 UTC, aaronsteers commented
@pandemicsyn - would you like to try to fit this in to `2.0.1`?

2022-06-09 21:11 UTC, aaronsteers commented
@pandemicsyn - I'm gonna go ahead and start the release process. If it finishes before I publish, happy to include - but also totally fine if not.

2022-06-09 21:12 UTC, pandemicsyn commented
@aaronsteers depends on how important config is, i think its done but it could use a once over from @pnadolny13 

I think this does cover most of the success cases, and because this command uses a command group - i was able to initialize all the important contexts early on - so even a failure should have the plugin context attached (as long as the plugin was valid). 

There are a few edge cases where I can't fire a failure event currently (like if you pass in to many args to `unset`) but we should get those when we implement exit events.

2022-06-09 21:16 UTC, pandemicsyn commented
@aaronsteers IMHO this ones not critical and we already got the big ones merged `invoke` , `elt`, `run`, `add`, `install`. I'd think this one is fine to go out in 2.0.2.

2022-06-14 14:47 UTC, pandemicsyn commented
Note: https://github.com/meltano/meltano/pull/6148 has a bunch of clean up that will impact this PR.

2022-06-14 17:47 UTC, pandemicsyn commented
Refactored to work with #6148 , should be good to go.

2022-06-16 19:39 UTC, cjohnhanson requested changes

2022-06-16 20:45 UTC, pandemicsyn commented on src/meltano/cli/config.py
> +    tracker.add_contexts(PluginsTrackingContext([(plugin, None)]))
https://github.com/meltano/meltano/pull/6137/commits/48070fe784bec08717b9c94f9b336d5de9ab6c85

2022-06-16 20:54 UTC, cjohnhanson approved these changes

2022-06-16 20:59 UTC, edgarrmondragon approved these changes

2022-06-16 21:01 UTC, pandemicsyn commented
sorry for the "draft" -> "ready for review" spam. Intended to flip a different PR back to draft.

2022-06-16 21:01 UTC, merged