Add missing `disable_tracking` setting entry
meltano/meltano pull request #6233
Opened 2022-06-17 21:27 UTC by aaronsteers

We discovered in https://github.com/meltano/meltano/pull/6199

2022-06-17 21:28 UTC, pandemicsyn approved these changes

2022-06-17 21:34 UTC, WillDaSilva approved these changes

2022-06-18 00:55 UTC, edgarrmondragon approved these changes

2022-06-26 03:10 UTC, WillDaSilva requested changes, later dismissed

2022-06-26 03:10 UTC, WillDaSilva commented on src/meltano/core/bundle/settings.yml
> +  # env_aliases: ["!MELTANO_DISABLE_TRACKING"]
This duplicate line should be removed.

```suggestion
```

2022-06-27 13:35 UTC, merged