ci: add config and docs for semantic-prs
meltano/meltano pull request #6248
Opened 2022-06-21 02:03 UTC by aaronsteers

This PR preps us to turn on Semantic PRs checks, which would significantly streamline release notes generation.

Modeled after the same in the SDK, and as discussed in our gitops discussion:

- https://github.com/meltano/gitops/issues/6

Attn: @tayloramurphy, @afolson, @edgarrmondragon, @pandemicsyn, @meltano/engineering 

Turning on the App integration just takes 5 minutes. I'll do that at the same time as merging this.

2022-06-21 02:19 UTC, tayloramurphy commented
@aaronsteers can you update https://docs.meltano.com/contribute/merge to reflect this new requirement?

2022-06-21 02:20 UTC, tayloramurphy requested changes
@aaronsteers can you update https://docs.meltano.com/contribute/merge with the new guidelines?

2022-06-21 03:36 UTC, edgarrmondragon requested changes

2022-06-21 03:36 UTC, edgarrmondragon commented on .github/semantic.yml
> +  - cli     # cookiecutters
copy-pasted:

```suggestion
  - ui
  - core
  - cli
```

2022-06-21 15:56 UTC, tayloramurphy commented on docs/src/_contribute/merge.md
> +The `meltano` repo uses the [semantic-prs](https://github.com/Ezard/semantic-prs) GitHub app to check all PRs againts the conventional commit syntax.
```suggestion
The `meltano` repo uses the [semantic-prs](https://github.com/Ezard/semantic-prs) GitHub app to check all PRs againts the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) syntax.
```

2022-06-21 15:58 UTC, tayloramurphy approved these changes

2022-06-21 16:06 UTC, edgarrmondragon approved these changes
lgtm!

2022-06-22 16:33 UTC, pandemicsyn approved these changes
❤️

2022-06-24 19:08 UTC, merged