feat: Resolve #3419 "Change default meltano config behavior to --no-environment"
meltano/meltano pull request #6327
Opened 2022-06-30 11:53 UTC by kgpayne

Closes #3419

- #3419

This PR:
- adds `deactivate_environmnent` to the `Project` class
- deactivates the active environment for `meltano config` if the default if the current active environment was sourced from the default (i.e. no `--environment` was chosen explicitly)
- adds an `info` log line to inform users of this behaviour and to direct them to use `--environment` to target an environment

2022-07-05 14:15 UTC, afolson approved these changes

2022-07-05 16:37 UTC, kgpayne commented
@aaronsteers @tayloramurphy as per the updated PR description, this also opts `meltano select` out of the `default_environment` (in addition to `meltano config`). I found when testing that `select` is often used alongside `config` and is essentially just another kind of config. We don't _have_ to treat these commands the same, and its simple to revert if prefer that `select` should still adhere to the `default_environment` 👍

2022-07-05 21:53 UTC, edgarrmondragon approved these changes

2022-07-05 22:36 UTC, edgarrmondragon approved these changes
@kgpayne this looks to me. I just left some comments on the logged messages.

2022-07-05 22:36 UTC, edgarrmondragon commented on src/meltano/cli/config.py
> +            f"Deactivated Environment '{project.active_environment.name}' (the default) as the `meltano config` command does not adhere to your projects `default_environment`. "
This wording sounds a little weird to me. It makes it seem like the specific value of `default_environment` is incompatible with `meltano config`, while it's just that the setting is ignored for `meltano config`. So how about

```suggestion
            f"The default environment ({project.active_environment.name}) will be ignored for `meltano config`."
```

2022-07-05 22:36 UTC, edgarrmondragon commented on src/meltano/cli/select.py
> +        )
Ditto the comment above

2022-07-06 14:10 UTC, tayloramurphy requested changes
@kgpayne I think it could make sense to change the default for `select` to be no-environment as well, but I'd like to keep this PR focused on just `config`. If you could open a discussion on this topic with the argument around `select` and possibly other topics that'd be helpful. We can pull each command into separate issues as we figure that out.

For this PR, can you also update https://docs.meltano.com/reference/command-line-interface#using-config-with-environments to make it clear the default behavior?

2022-07-06 18:13 UTC, tayloramurphy requested changes

2022-07-08 20:09 UTC, tayloramurphy requested changes
I've tested locally and it seems to work. I've opened:

- https://github.com/meltano/meltano/issues/6390 which highlights a new thing I think we should do. 

I'm also not too keen on having:

```
2022-07-08T19:48:50.200082Z [info     ] Environment 'dev' is active
2022-07-08T19:48:50.566516Z [info     ] The default environment (dev) will be ignored for `meltano config`. To configure a specific Environment, please use option `--environment=<environment name>`.
``` 

which seem to be saying conflicting things. I'll file a follow-up issue to address that UX. We may need to move the invocation of that not at the start of the CLI but only once we know what command you're trying to do.

2022-07-08 20:09 UTC, tayloramurphy commented on docs/example-library/meltano-basics/index.md
> +meltano --environment=dev config tap-gitlab set start_date 2022-04-25T00:00:01Z
@kgpayne I'd like this test case to be updated to include setting the config globally. I think you could drop https://github.com/meltano/meltano/blob/main/docs/example-library/meltano-basics/meltano.yml#L11 and then add the configuration to validate it does it globally. 

As it stands the integration tests aren't capturing the new behavior.

2022-07-13 17:17 UTC, tayloramurphy commented on docs/example-library/meltano-basics/index.md
> +meltano --environment=dev config tap-gitlab set start_date 2022-04-25T00:00:01Z
Looks like you just added it! Approving!

2022-07-13 17:17 UTC, tayloramurphy approved these changes
Test case is added!

2022-07-13 22:27 UTC, merged