ci: Use Nox to test installed package
meltano/meltano pull request #6395
Opened 2022-07-10 23:27 UTC by edgarrmondragon

2022-07-26 06:24 UTC, edgarrmondragon commented
Failing jobs due to:

- On Windows + Python 3.7, asyncio's `create_subprocess_exec` is seemingly broken
- On Windows + Python 3.10, the `docker` dev dependency is not compatible

2022-07-27 19:08 UTC, pandemicsyn approved these changes

2022-07-27 19:55 UTC, WillDaSilva reviewed
The changes look great, but if we merge this in it'll result in CI failures for all PRs that merge in `main`. I'd rather consider this blocked by
- https://github.com/meltano/meltano/issues/6479

and mark it as a draft until that is resolved.

2022-07-27 21:09 UTC, edgarrmondragon commented
> The changes look great, but if we merge this in it'll result in CI failures for all PRs that merge in `main`. I'd rather consider this blocked by

@WillDaSilva what do you think we should fix before merging this PR?

1. the fact that we're not running tests on Windows x Python 3.7,3.10 or
2. or the failing tests themselves

I feel like `1` is fairly easy, while `2` is a more complex and I don't think we're in a position to solve quickly. Wdyt?

cc @aaronsteers wdyt about this? 👆

2022-07-27 21:44 UTC, WillDaSilva commented
> what do you think we should fix before merging this PR?
> 
>     1. the fact that we're not running tests on Windows x Python 3.7,3.10 or
> 
>     2. the failing tests themselves
> 
> 
> I feel like `1` is fairly easy to tackle on its own (or by merging this PR), while `2` is a more complex and I don't think we're in a position to solve quickly. Wdyt?

@edgarrmondragon I was referring to 2, but upon second thought, we could just have this PR comment out the Windows tests from the matrix for 3.7 and 3.10. That way we can merge this in immediately, and not have it cause failures for all other PRs, *and* be in a better position than we were before wrt Windows test coverage. There's no need for us to wait till those tests are actually fixed to get this PR merged in.

2022-07-27 21:46 UTC, WillDaSilva requested changes

2022-07-27 21:46 UTC, WillDaSilva commented on .github/workflows/test.yml
> +        - { python-version: "3.10", os: "windows-2022",   backend-db: sqlite }
```suggestion
        # We'd like to run Windows tests for all backend-dbs see https://github.com/meltano/meltano/issues/6281
        # Windows tests for Python 3.7 and 3.10 are temporarily disabled - see https://github.com/meltano/meltano/issues/6479
        # - { python-version: "3.7",  os: "windows-2022",   backend-db: sqlite }
        - { python-version: "3.8",  os: "windows-2022",   backend-db: sqlite }
        - { python-version: "3.9",  os: "windows-2022",   backend-db: sqlite }
        # - { python-version: "3.10", os: "windows-2022",   backend-db: sqlite }
```

2022-07-27 22:21 UTC, WillDaSilva approved these changes

2022-07-28 17:24 UTC, merged