docs: Document overriding capabilities and extending settings
meltano/meltano pull request #6411
Opened 2022-07-13 09:21 UTC by edgarrmondragon

2022-07-13 09:23 UTC, edgarrmondragon commented
Docs preview: https://deploy-preview-6411--meltano.netlify.app/guide/configuration#overriding-discoverable-plugin-properties

2022-07-13 15:34 UTC, tayloramurphy requested changes

2022-07-13 20:19 UTC, edgarrmondragon commented on docs/src/_guide/configuration.md
> +Starting with Meltano [`2.0`](/reference/v2-migration), you can override the properties of discoverable plugins and extend the default [`settings`](/reference/settings):
> is there anything else besides capabilities and settings that can be overridden?

@tayloramurphy `settings_group_validation` too. Is that worth documenting explicitly too?

2022-07-13 20:25 UTC, tayloramurphy commented on docs/src/_guide/configuration.md
> +Starting with Meltano [`2.0`](/reference/v2-migration), you can override the properties of discoverable plugins and extend the default [`settings`](/reference/settings):
@edgarrmondragon I think it's worth it. 

Question on the behavior, `capabilities` are fully overridden such that it's a full array replacement, right?

For settings though, does it always append or is it actually comparing each setting and doing a replacement if there's a match? Specific example, if the plugin defines a setting as having type string but the users overrides the type for that setting with type: integer, will there be duplicate settings or is it a smarter merge?

2022-07-13 21:20 UTC, edgarrmondragon commented on docs/src/_guide/configuration.md
> +Starting with Meltano [`2.0`](/reference/v2-migration), you can override the properties of discoverable plugins and extend the default [`settings`](/reference/settings):
> `capabilities` are fully overridden such that it's a full array replacement, right?

@tayloramurphy correct, they're fully replaced, not extended.

> For settings though, does it always append or is it actually comparing each setting and doing a replacement if there's a match? Specific example, if the plugin defines a setting as having type string but the users overrides the type for that setting with type: integer, will there be duplicate settings or is it a smarter merge?

If there's a collision on name, then the setting, say `token`, is taken from the override definition in `meltano.yml` and used at runtime, while the `token` setting definition in the lockfile is discarded. So no, there aren't any duplicates 🙂.

2022-07-13 21:32 UTC, tayloramurphy commented on docs/src/_guide/configuration.md
> +Starting with Meltano [`2.0`](/reference/v2-migration), you can override the properties of discoverable plugins and extend the default [`settings`](/reference/settings):
@edgarrmondragon all of that context is worth adding then please 😄

2022-07-14 19:44 UTC, tayloramurphy commented on docs/src/_guide/configuration.md
> +All overrides replace the values of in the [lockfile](/concepts/plugins#lock-artifacts), except for `settings`, which extend the base definitions. If there is a collision on name, then the setting is
```suggestion
All overrides replace the values stored in the [lockfile](/concepts/plugins#lock-artifacts), except for `settings`, which extend the base definitions. If there is a collision on name, then the setting is taken from the override definition in `meltano.yml` and used at runtime, while the token setting definition in the lockfile is discarded.
```

2022-07-14 19:44 UTC, tayloramurphy approved these changes

2022-07-14 21:08 UTC, merged