fix: Remove check for command in InvokerBase
meltano/meltano pull request #6431
Opened 2022-07-15 18:21 UTC by cjohnhanson

Closes #6188

2022-07-15 18:49 UTC, edgarrmondragon approved these changes

2022-07-15 21:22 UTC, tayloramurphy requested changes
@cjohnhanson this needs a doc change as well - see pt. 3 https://docs.meltano.com/reference/command-line-interface#tasks

2022-07-18 19:05 UTC, pandemicsyn approved these changes
lgtm. Small nit (feel free to ignore). Similar to what Taylor mentioned, wonder if we should clarify usage. Might be worth updating `cli/run.py` usage to say:

```
      Run a set of command blocks in series.

      Blocks are specified as a list of plugin names, e.g.     `meltano run
      some_extractor some_loader some_plugin:some_optional_command` and are run in the
      order they are specified from left to right. A failure in any block
      will cause the entire run to abort.
```

To flag that the command is optional?

2022-07-18 22:03 UTC, tayloramurphy approved these changes

2022-07-19 00:03 UTC, merged