chore(deps): Pin werkzeug to <2.2.0
meltano/meltano pull request #6470
Opened 2022-07-24 16:01 UTC by edgarrmondragon

2022-07-24 16:33 UTC, WillDaSilva requested changes

2022-07-24 16:33 UTC, WillDaSilva commented on pyproject.toml
> +werkzeug = "<=2.1.3"
```suggestion
werkzeug = ">=2.1,<=2.1.3"
```

`poetry.lock` will have to be re-generated if this change is applied.

2022-07-24 16:37 UTC, WillDaSilva approved these changes

2022-07-25 14:14 UTC, merged

2022-07-25 14:19 UTC, edgarrmondragon commented
Confirmed that this uses the right constraint:

```console
$ meltano@6470 --version                                                                                                                           
meltano, version 2.3.0
```