docs: update custom extractor tutorial
meltano/meltano pull request #6703
Opened 2022-09-02 06:47 UTC by jared-rimmer

I have ported over and merged content from:

https://meltano.com/blog/how-to-build-a-custom-extractor-with-meltano/

with the existing custom extractor tutorial in an attempt to making it a one stop shop for people wanting to get started with a creating a custom extractor.

Open questions

- **Terminology**: I've used "custom extractor" throughout and changed references from tap, plugin, project, source. What are your thoughts on this?
- **SEO**: As a lot of the content is a literal copy and paste from the blog it might have implications of duplicate content. Would you prefer a more thorough rewrite?

2022-09-02 19:38 UTC, tayloramurphy commented
@afolson you know more about SEO than me - what's our preference on this? cc @lauraperezco

2022-09-05 14:16 UTC, lauraperezco commented
> @afolson you know more about SEO than me - what's our preference on this? cc @lauraperezco

@tayloramurphy same as the ELT page applies here, the main website has preference over subpages for SEO, so Jared's assesment is _correct_! I think ideally we should replace the current content in docs with a short introduction that takes you to the blog link for the full tutorial (and maybe reference some other blog-tutorials in the future to make this section in docs more complete while giving more authority to our website)

2022-09-05 16:03 UTC, edgarrmondragon requested changes

2022-09-05 16:03 UTC, edgarrmondragon commented on CHANGELOG.md
> +* Update custom extractor tutorial content
This isn't needed as the changelog entry will be taken from the merge commit from this PR 🙂 
```suggestion
```

2022-09-06 08:43 UTC, jared-rimmer commented
@lauraperezco happy to update with your suggestions 👍 

From the [Slack thread](https://meltano.slack.com/archives/C013Z450LCD/p1661512073303649) there was an aim to make the docs the place where users can find all this type of information. Linking out to blogs still achieves this

2022-09-09 07:13 UTC, sbalnojan commented
Hey @jared-rimmer, no the PR can stay as it is, everything in once place. 

But FWIW we're aware that we need to figure out a guide for what goes where, that's still WIP ;)

2022-09-12 22:25 UTC, edgarrmondragon submitted a review, later dismissed

2022-09-12 22:25 UTC, edgarrmondragon commented on docs/src/_tutorials/custom-extractor.md
> +- Choose jsonplaceholder as your source name
```suggestion
- Type `jsonplaceholder` as your source name
```

2022-09-12 22:25 UTC, edgarrmondragon commented on docs/src/_tutorials/custom-extractor.md
> +Choose from 1, 2, 3, 4, 5, 6 [1]: 6
```suggestion
1 - API Key
2 - Bearer Token
3 - Basic Auth
4 - OAuth2
5 - JWT
6 - Custom or N/A
Choose from 1, 2, 3, 4, 5, 6 [1]: 6
```

2022-09-12 22:25 UTC, edgarrmondragon commented on docs/src/_tutorials/custom-extractor.md
> +Choose from 1, 2 [1]:
```suggestion
1 - GitHub
2 - None (Skip)
Choose from 1, 2 [1]:
```

2022-09-12 22:25 UTC, edgarrmondragon commented on docs/src/_tutorials/custom-extractor.md
> +The result of the above command is a new directory—tap-jsonplaceholder—that contains boilerplate code for developing your tap and also a meltano.yml file that you can use to test your custom extracto
```suggestion
The result of the above command is a new directory `tap-jsonplaceholder` that contains boilerplate code for developing your tap and also a `meltano.yml` file that you can use to test your custom extractor.
```

2022-09-12 22:25 UTC, edgarrmondragon commented on docs/src/_tutorials/custom-extractor.md
> +).to_dict()
```suggestion
class CommentsStream(jsonplaceholderStream):
    primary_keys = ["id"]
    path = '/comments'
    name = "comments"
    schema = th.PropertiesList(
        th.Property("postId", th.IntegerType),
        th.Property("id", th.IntegerType),
        th.Property("name", th.StringType),
        th.Property("email", th.StringType),
        th.Property("body", th.StringType),
    ).to_dict()
```

2022-10-06 09:08 UTC, sbalnojan approved these changes
all changes adressed!

2022-10-06 09:10 UTC, merged