docs: add update pip to install
meltano/meltano pull request #6880
Opened 2022-10-13 07:04 UTC by sbalnojan

as discussed in https://github.com/meltano/meltano/issues/3112

2022-10-13 14:50 UTC, WillDaSilva requested changes

2022-10-13 14:50 UTC, WillDaSilva commented on docs/src/_getting-started/installation.md
>  $ pip install "meltano"
There should be consistency between these two `pip` invocations. Using `pip` on its own should be safe, or at least no safer than `python -m pip` (compared to `python3 -m pip` :unamused:).

```suggestion
$ pip install --upgrade pip
Requirement already satisfied.
$ pip install "meltano"
```

2022-10-13 15:40 UTC, tayloramurphy approved these changes

2022-10-17 12:22 UTC, WillDaSilva approved these changes

2022-10-17 14:18 UTC, merged