Add `--force` option to ignore existing files/directories in an non-empty project directory with `meltano init`
meltano/meltano pull request #6927
Opened 2022-10-24 20:07 UTC by ReubenFrankel

One of the primary use-cases addressed by #6806 was to be able to create an empty repository in GitHub, clone into a directory and immediately `meltano init` into it. I completely forgot about this when implementing #6814, so this is the follow-up PR! :sweat_smile: 

See [this Slack thread](https://meltano.slack.com/archives/C013Z450LCD/p1666396209017099) for more information.

2022-10-24 20:16 UTC, tayloramurphy requested changes
Documentation update on this please :) https://docs.meltano.com/reference/command-line-interface#init

Also - if there is a matching file / folder, I'm assuming it would get overwritten, correct? Would be good to call that out in the docs.

2022-10-24 21:06 UTC, ReubenFrankel commented
@tayloramurphy Given the contents of a new project, what are your thoughts on overwriting vs throwing an error on a conflict? I was leaning towards the latter since there is already protection against running `meltano init` within an existing Meltano project, and I didn't really want to start overwriting things without explicit user confirmation. Since `meltano init` doesn't prompt on file conflicts currently anyway, maybe `--force` is the wrong option name?

2022-10-24 21:20 UTC, tayloramurphy commented
> Given the contents of a new project, what are your thoughts on overwriting vs throwing an error on a conflict? I was leaning towards the latter since there is already protection against running `meltano init` within an existing Meltano project, and I didn't really want to start overwriting things without explicit user confirmation. Since `meltano init` doesn't prompt on file conflicts currently anyway, maybe `--force` is the wrong option name?

@ReubenFrankel `--force` is probably the wrong one argument in this case. What about something like:

`meltano init --ignore-files --force`

where `--ignore-files` does what's implemented here and writes the Meltano files ignoring existing ones, but errors if there is a conflict. `--force` would then just blast away everything if there is a conflict. 

I'd also be open to `--ignore-existing` or something else if there's a better option.

2022-10-25 01:53 UTC, ReubenFrankel commented
@tayloramurphy

> where --ignore-files does what's implemented here and writes the Meltano files ignoring existing ones, but errors if there is a conflict.

There were some comments raised in the original issue about improving onboarding. I think it would be a more seamless experience for new users if `meltano init` could create a project in *any* directory (barring conflicts), like `git init` can. This would then remove the need for a new `--ignore-existing` or similar option. Do you think that could work, or does it just complicate things too much?

> --force would then just blast away everything if there is a conflict.

Not sure where this leaves `--force` as described here. Maybe out-of-scope for this PR?

2022-10-25 19:44 UTC, aaronsteers commented
@ReubenFrankel, @tayloramurphy - I'm okay dropping `--force` and just making this the default behavior, so long as this default is still 'safe' and that we check that there aren't any other collisions, for instance that `meltano.yml` does not already exist.

The challenge here though is that our default implementation installs a bunch of files and paths. After getting 50% through the `init`, if we fail on the 5th file (for instance), we would not want to leave the target folder in a bad or incomplete state.

@ReubenFrankel - Do you think we can ensure safety of the command before running it, so that '--force' or similar "opt in" behavioral flags are not needed?

If we do need an opt in though, then I'm totally fine with using something like `--ignore-existing`, as I can understand that `--force` implies files would be overriden in case of conflict - which is not the primary use case we're trying to handle here.

2022-10-25 20:57 UTC, tayloramurphy commented
> The challenge here though is that our default implementation installs a bunch of files and paths. After getting 50% through the init, if we fail on the 5th file (for instance), we would not want to leave the target folder in a bad or incomplete state.

Yeah, the difference of `git init` is that it's creating a single hidden directory whereas Meltano is a bit more aggressive about what it's creating. I'm with AJ on assuring safety and cleanup to keep it as a default, but if not, then making it an explicit opt in.

2022-10-25 22:21 UTC, ReubenFrankel commented
@aaronsteers @tayloramurphy Yeah, I'm confident we can implement a check for potential conflicts before anything is actually created. I'll close this PR and open a separate one - appreciate your input! :smile:

2022-10-25 22:21 UTC, closed without merging