feat: Make `no_color` available as a project setting
meltano/meltano pull request #6946
Opened 2022-10-28 23:01 UTC by edgarrmondragon

Closes https://github.com/meltano/meltano/issues/6940

2022-11-01 17:23 UTC, tayloramurphy approved these changes

2022-11-01 19:31 UTC, WillDaSilva approved these changes

2022-11-01 19:31 UTC, WillDaSilva commented on docs/src/_reference/settings.md
> +```
You may want to indicate that only one of these 3 command need be run.

2022-11-01 19:58 UTC, aaronsteers requested changes
Requesting we hold on this. Converting things to project settings has sometimes created new issues. I'd want to better understand any potential impacts versus benefits before moving forward.

2023-05-25 14:03 UTC, tayloramurphy commented
@WillDaSilva @edgarrmondragon how are we feeling about this PR?

2023-05-26 15:21 UTC, edgarrmondragon commented
> @WillDaSilva @edgarrmondragon how are we feeling about this PR?

@tayloramurphy It seems tests are failing, probably related to changes done in the interim to how project and settings are managed under the hood. It's probably take me a full day to figure out what's changed and update the PR.

2023-09-18 16:48 UTC, edgarrmondragon commented
Closing this to keep things clean. If we reprioritize, we can start  a clean PR.

2023-09-18 16:48 UTC, closed without merging