docs: Expand UI deprecation description
meltano/meltano pull request #7041
Opened 2022-11-30 22:40 UTC by qbatten

Small docs PR to resolve issue #7038, per convo in office hours on 11/30. Thanks to @Sburwash for pointing out that the Airflow webserver can replace nearly all Meltano UI functionality.

Maintainers please do add or edit, I wasn't sure what other features are/aren't supported by UI, nor do I know the details of how the UI/environments interact, just think I remember someone saying they dont play nice together. Thanks!

2022-11-30 23:28 UTC, edgarrmondragon requested changes

2022-11-30 23:28 UTC, edgarrmondragon commented on docs/src/_guide/troubleshooting.md
> +- Schedules based on ELT (`meltano schedule add <schedule_name> --extractor <tap> --loader <target> --transform ...`)
```suggestion
- Schedules based on [the `elt` command](https://docs.meltano.com/reference/command-line-interface#elt) (`meltano schedule add <schedule_name> --extractor <tap> --loader <target> --transform ...`)
```

2022-11-30 23:28 UTC, edgarrmondragon commented on docs/src/_guide/troubleshooting.md
> +- Schedules based on jobs (`meltano schedule add <schedule_name> --job <job>`)
```suggestion
- Schedules based on [jobs](https://docs.meltano.com/reference/command-line-interface#job) (`meltano schedule add <schedule_name> --job <job>`)
```

2022-11-30 23:28 UTC, edgarrmondragon commented on docs/src/_guide/troubleshooting.md
> +- Environments
```suggestion
- [Environments](https://docs.meltano.com/concepts/environments)
```

2022-12-01 08:23 UTC, aaronsteers commented on docs/src/_guide/troubleshooting.md
> +If you're using Airflow as your orchestrator, the Airflow webserver UI should be able to serve as a replacement for many Meltano UI use cases. See the ["Airflow orchestrator" section of the "Deployme
```suggestion
If you're using [Airflow](https://hub.meltano.com/utilities/airflow) or [Dagster](https://hub.meltano.com/utilities/dagster) as your orchestrator, the Airflow or Dagster webserver UI should be able to serve as a replacement for many Meltano UI use cases. 

If using Airflow as orchestrator, see the ["Airflow orchestrator" section of the "Deployment in Production" guide](/guide/production#airflow-orchestrator) for more details on how to get the webserver running. From the webserver, you can [view all DAGs](https://airflow.apache.org/docs/apache-airflow/1.10.14/ui.html#dags-view). You can also access the Meltano logs for a specific task instance by going to the [task instance context menu](https://airflow.apache.org/docs/apache-airflow/1.10.14/ui.html#task-instance-context-menu) and clicking "Log" or "View logs".
```

2022-12-01 18:51 UTC, edgarrmondragon commented on docs/src/_guide/troubleshooting.md
> +If you're using [Airflow](https://hub.meltano.com/utilities/airflow) or [Dagster](https://hub.meltano.com/utilities/dagster) as your orchestrator, the Airflow or Dagster webserver UI should be able t
```suggestion
If you're using [Airflow](https://hub.meltano.com/utilities/airflow) or [Dagster](https://hub.meltano.com/utilities/dagster) as your orchestrator, the Airflow or Dagster webserver UI should be able to serve as a replacement for many Meltano UI use cases.
```

2022-12-01 18:54 UTC, edgarrmondragon approved these changes

2022-12-02 15:01 UTC, afolson approved these changes

2022-12-02 15:03 UTC, merged

2022-12-02 15:03 UTC, afolson commented
@qbatten This looks great, thanks!