add EDK details and context around switching to utilities
meltano/meltano pull request #7239
Opened 2023-01-30 22:30 UTC by pnadolny13

Related to https://github.com/meltano/hub/issues/1115 and https://github.com/meltano/hub/pull/1135.

We didn't have anything in the docs about the EDK and why it exists. As I was writing this I thought giving the context would be helpful but let me know what you think.

2023-01-31 16:49 UTC, tayloramurphy requested changes
@pnadolny13 love this. Minor edits

2023-01-31 16:49 UTC, tayloramurphy commented on docs/src/_guide/advanced-topics.md
> +Meltano extensions are thin wrappers around applications that allow you to integrate existing data tools with Meltano.
```suggestion
Meltano extensions are lightweight shims that allow you to integrate existing data tools with Meltano.
```

Thoughts on this language? I don't want to give the impression that we fully wrap the tool and that our Airflow is somehow different from a "pure" Airflow

2023-01-31 16:49 UTC, tayloramurphy commented on docs/src/_guide/advanced-topics.md
> +Extensions allow the developer to add additional features like pre and post hooks to run before and after Meltano executes the wrapped application.
```suggestion
Extensions allow the developer to add additional features like pre/post-hooks to run before/after Meltano executes the application, as well enabling project scaffolding to be customized for each plugin. This project scaffolding was previously accomplished via files bundles.
```

2023-01-31 16:49 UTC, tayloramurphy commented on docs/src/_guide/advanced-topics.md
> +For more information on how to build your own EDK-based Meltano extension, see [the EDK docs](https://edk.meltano.com/en/latest/).
```suggestion

The Meltano [Extension Developer Kit](https://github.com/meltano/edk) (EDK) was created to make it easier for developers to build Meltano extensions.
For more information on how to build your own EDK-based Meltano extension, see [the EDK docs](https://edk.meltano.com/en/latest/).
```

2023-01-31 16:49 UTC, tayloramurphy commented on docs/src/_guide/advanced-topics.md
> +* utility - now also including transformers and orchestrators
```suggestion
* utility - now also including plugins previously called transformers and orchestrators
```

2023-01-31 17:36 UTC, pnadolny13 commented
@tayloramurphy thanks for the suggestions! I agree with you comment on the `shims` wording. Let me know if you have any other thoughts.

2023-02-01 16:23 UTC, tayloramurphy approved these changes
This looks good to me. I'm approving but let's hold off on merging until we coordinate with Engineering on the Hub PR as well and make sure they're aware and have reviewed.

2023-02-01 22:58 UTC, tayloramurphy commented
@aaronsteers I'd like your review on this prior to merging. Target date of Friday merge.

2023-02-02 05:20 UTC, aaronsteers approved these changes
A few notes. Feel free to resolve as you see fit and merge if nothing else outstanding. Thanks!

2023-02-02 05:20 UTC, aaronsteers commented on docs/src/_guide/advanced-topics.md
> +Meltano extensions are lightweight shims that allow you to integrate existing data tools with Meltano.
Shim can often mean something different. A different word here could be more accurate. Something like...

```suggestion
Meltano extensions are lightweight executables which allow you to integrate existing data tools with Meltano.
```

```suggestion
Meltano extensions are lightweight programs which allow you to integrate existing data tools with Meltano.
```

2023-02-02 05:20 UTC, aaronsteers commented on docs/src/_guide/advanced-topics.md
> +### EDK Context
This section is more about how Meltano is classifying plugins and less about the EDK itself - as the EDK itself is agnostic to the plugin type we place upon it.


```suggestion
### Meltano Plugin Types
```

Or something like

```suggestion
### Meltano Utilities
```

Or

```suggestion
### Selecting a Plugin Type
```

Or

```suggestion
### Understanding Plugin Types
```

2023-02-02 16:30 UTC, merged