fix: Restrict Azure state logging to WARNING and above
meltano/meltano pull request #7725
Opened 2023-06-01 08:24 UTC by acarter24

Closes #7723

2023-06-01 14:39 UTC, WillDaSilva commented on src/meltano/core/logging/utils.py
> +            "azure.core.pipeline.policies.http_logging_policy": {  # see #7723 , azure http logs at info level, too noisy
```suggestion
            # Azure HTTP logs at info level are too noisy; see
            # https://github.com/meltano/meltano/issues/7723
            "azure.core.pipeline.policies.http_logging_policy": {
```

2023-06-01 16:40 UTC, edgarrmondragon requested changes

2023-06-01 16:40 UTC, edgarrmondragon commented on src/meltano/core/logging/utils.py
> +            },
I think we can also achieve the desired behavior if we omit `handlers` and enable `propagate`

```suggestion
                "level": logging.WARNING,
                "propagate": True,
            },
```

2023-06-02 19:08 UTC, edgarrmondragon commented
@acarter24 I can't push to your fork's `main` branch but this changes seem to work fine:

```diff
                 "propagate": True,
             },
             "snowplow_tracker.emitters": {
-                "handlers": ["console"],
                 "level": logging.ERROR,
             },
             "urllib3": {
-                "handlers": ["console"],
                 "level": logging.INFO,
-                "propagate": False,
             },
             "asyncio": {
-                "handlers": ["console"],
                 "level": logging.INFO,
-                "propagate": False,
             },
             # Azure HTTP logs at info level are too noisy; see
             # https://github.com/meltano/meltano/issues/7723
             "azure.core.pipeline.policies.http_logging_policy": {
-                "handlers": ["console"],
                 "level": logging.WARNING,
-                "propagate": False,
             },
         },
     }
```

2023-06-12 15:51 UTC, WillDaSilva commented
Thanks for the updates @acarter24

@edgarrmondragon is on vacation, and will be back on the 19th or 20th.

He knows this PR and code better than I, but if you feel this is sufficiently urgent (i.e. it's causing problems for you and you would like the fix to be released in a new version of Meltano sooner rather than later) I can review this today or tomorrow. What would you prefer @acarter24?

2023-06-21 19:33 UTC, edgarrmondragon approved these changes
Thanks @acarter24!

2023-06-21 19:34 UTC, merged