feat: Added `--force` CLI flag for meltano `add` command.
meltano/meltano pull request #8169
Opened 2023-09-20 19:15 UTC by XshubhamX

**Additions:**

1. Added the `--force` flag support for `add` command.
2. Added test.
3. Updated the doc for the same

cc @WillDaSilva

2023-09-20 19:27 UTC, edgarrmondragon requested changes
Thanks @XshubhamX! Requested a few changes.

2023-09-20 19:27 UTC, edgarrmondragon commented on docs/docs/reference/command-line-interface.md
> +The `--force` will ignore the required Python version declared by the plugins.
Can you move this to the `Parameters` section of this command below?

2023-09-20 19:27 UTC, edgarrmondragon commented on tests/meltano/cli/test_add.py
> +                cli, ["add", "transform", "tap-google-analytics", "--force"]
```suggestion
                cli,
                ["add", "transform", "tap-google-analytics", "--force"],
```

2023-09-20 19:27 UTC, edgarrmondragon commented on docs/docs/reference/command-line-interface.md
> +meltano add extractor tap-gitlab --force
```suggestion
meltano add extractor tap-gitlab --force
```

2023-09-20 19:27 UTC, edgarrmondragon commented on docs/docs/reference/command-line-interface.md
Let's add a similar section to what we have for `install` above the `Note: Unlike...` note:

> If the plugin you are trying to add declares that it does not support the version of Python you are using, but you want to attempt to use it anyway, you can override the Python version restriction by providing the `--force` flag to `meltano add`.

2023-09-20 19:29 UTC, WillDaSilva commented on docs/docs/reference/command-line-interface.md
> +# Or you can also add a package forcefully using --force flag
```suggestion
# You can ignore the required Python declared by a plugin by using --force flag
```

2023-09-20 19:32 UTC, edgarrmondragon commented
You might wanna update instances of `install_plugin_mock.assert_called_*` to check the `force` parameter you're now passing it.

2023-09-21 12:27 UTC, ReubenFrankel commented
Great timing! :smile: We discussed this exact feature recently here: https://github.com/meltano/meltano/pull/7907#issuecomment-1708096810

Will this work as described in #8110?

> As discussed in #7907, a `--force` (or similar) flag would enable a plugin to be re-added to the project, regardless of whether or not the plugin already exists. This would essentially be a shortcut for:
>
> ```
> meltano remove <plugin type> <plugin name>
> meltano add <plugin type> <plugin name>
> ```
>
> This feature would be useful in resetting a plugin definition that perhaps isn't quite working after some user changes, updating a custom plugin that doesn't have a `.lock` file (i.e. added from `--custom` or [`--from-ref`](#7907)), or converting from a custom plugin to the Hub definition once published.
>
> Adding a new plugin with this flag should just `meltano add` as normal.

2023-09-21 14:48 UTC, edgarrmondragon commented
> Great timing! 😄 We discussed this exact feature recently here: [#7907 (comment)](https://github.com/meltano/meltano/pull/7907#issuecomment-1708096810)
> 
> Will this work as described in #8110
> 
> > As discussed in #7907, a `--force` (or similar) flag would enable a plugin to be re-added to the project, regardless of whether or not the plugin already exists. This would essentially be a shortcut for:
> > ```
> > meltano remove <plugin type> <plugin name>
> > meltano add <plugin type> <plugin name>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This feature would be useful in resetting a plugin definition that perhaps isn't quite working after some user changes, updating a custom plugin that doesn't have a `.lock` file (i.e. added from `--custom` or [`--from-ref`](#7907)), or converting from a custom plugin to the Hub definition once published.
> > Adding a new plugin with this flag should just `meltano add` as normal.
> 
> , or is this just a way to pass `--force` to the implicit `meltano install` step of `meltano add`?

Oh good call @ReubenFrankel. This is NOT https://github.com/meltano/meltano/issues/8110 😬.

I didn't realize we had two feature requests that suggested the same flag for different ends:

* https://github.com/meltano/meltano/issues/8110
* https://github.com/meltano/meltano/issues/7277

2023-09-21 15:01 UTC, XshubhamX commented
@WillDaSilva @edgarrmondragon Please check the PR, I have made the required changes

2023-09-21 15:47 UTC, WillDaSilva commented
@XshubhamX @edgarrmondragon @ReubenFrankel I think `--force` is fine here (if only to maintain consistency with `meltano install`), and I'd suggest we use `--reinstall` for #8110. I've left a comment on #8110 with my thoughts:
- https://github.com/meltano/meltano/issues/8110#issuecomment-1729845907

Please let me know what you all think of this approach.

2023-09-21 15:52 UTC, ReubenFrankel commented
@edgarrmondragon @WillDaSilva I'm happy to be convinced otherwise, but I actually think the opposite. :sweat_smile: https://github.com/meltano/meltano/issues/8110#issuecomment-1729855158

2023-09-21 18:33 UTC, edgarrmondragon commented
@XshubhamX Let's use `--force-install` instead of `--force`. We can get rid of the short option `-f`.

2023-09-21 18:53 UTC, XshubhamX commented
> @XshubhamX With the context given [above](https://github.com/meltano/meltano/pull/8169#issuecomment-1729739870), what do you think of using a different flag name for this feature, e.g. `--force-install`. Alternatively, we could suggest a different flag for #8110. Not requesting changes at the moment, just trying to get your thoughts on it.
> 
> cc @WillDaSilva @ReubenFrankel

I also think that using --force-install flag instead of --force flag quite fits with the already existing --no-install flag implementation.

2023-09-21 18:56 UTC, edgarrmondragon commented
@XshubhamX Given the additional context in https://github.com/meltano/meltano/issues/8110#issuecomment-1730124598, let's keep `--force` here.

Sorry for the back and forth 😅

2023-09-21 19:14 UTC, XshubhamX commented
> @XshubhamX Let's use `--force-install` instead of `--force`. We can get rid of the short option `-f`.

@edgarrmondragon  We are going ahead with this, right?

2023-09-21 19:23 UTC, edgarrmondragon commented
> > @XshubhamX Let's use `--force-install` instead of `--force`. We can get rid of the short option `-f`.
> 
> @edgarrmondragon We are going ahead with this, right?

Yeah, let's rename it :+1:

2023-09-21 19:42 UTC, XshubhamX commented
@edgarrmondragon PR is updated!

2023-09-22 15:48 UTC, edgarrmondragon approved these changes
Thanks @XshubhamX!

2023-09-22 15:51 UTC, merged