docs: Update contribution guidelines
meltano/meltano pull request #8200
Opened 2023-09-30 04:45 UTC by mjsqu

Closes https://github.com/meltano/meltano/issues/8199

Would appreciate some style tips about how to reference the version of nodejs - I tried to serve the docs using `npm start` with nodejs 12.22.12 installed (my stock Debian version), but got some errors:

```log
> docs.meltano.com@3.1.0 start
> docusaurus start

file:///home/mj2squ/repos/meltano/docs/node_modules/@docusaurus/core/bin/docusaurus.mjs:30
process.env.BABEL_ENV ??= 'development';
                       ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

These were fixed by install nodejs 20.8.0 from https://github.com/nodesource/distributions

2023-09-30 04:46 UTC, mjsqu commented
P.S. The new docusaurus docs look really great, and serving them (once I'd updated node) is a breeze 😄

2023-09-30 13:53 UTC, edgarrmondragon requested changes
Hey @mjsqu! Thanks for taking the time

2023-09-30 13:53 UTC, edgarrmondragon commented on docs/docs/contribute/docs.md
>  **Note:** Changes to `_config.yml` require you to stop the Jekyll server (`^C`) and restart it with `bundle exec jekyll serve`.
Let's get rid of this 😅

2023-09-30 16:54 UTC, mjsqu commented
There are a few more references to Jekyll later on the page, would be good if someone can work out if there's a new alternative or if these sections can be removed

2023-09-30 16:55 UTC, edgarrmondragon approved these changes

2023-09-30 16:56 UTC, edgarrmondragon commented
https://github.com/meltano/meltano/issues/8202

2023-10-02 16:25 UTC, tayloramurphy approved these changes

2023-10-02 17:55 UTC, merged